CREATE TABLE restaurantes(
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(1000) NOT NULL,
    telefone VARCHAR(12) NOT NULL,
    pontuacao NUMERIC(5,2),
    preco_entrega NUMERIC(5,2),
    endereco VARCHAR(255),
    criado_em TIMESTAMP default current_timestamp
);

CREATE TABLE pratos(
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(1000) NOT NULL,
    preco NUMERIC(5,2),
    criado_em TIMESTAMP default current_timestamp,
    restaurante_fk int4 references restaurantes(id)
);

CREATE TABLE Users(
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    hash_password VARCHAR(255) NOT NULL
);