CREATE TABLE restaurantes(
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(1000) NOT NULL,
    pontuacao NUMERIC(5,2),
    preco_entrega NUMERIC(5,2),
    criado_em TIMESTAMP default current_timestamp
);